### PR TITLE
Migrate from Orders API

### LINKED ISSUE #28: Orders API is deprecated
Stripe is sweeping this one under the rug. Relying on it isn't the most dangerous thing but it can only cause problems in the future. Already, Orders and Skus are inaccessible through the dashboard by default, as mentioned in #27 

We should move to Products and Prices, although we lose the ability to track inventory with Prices :disappointed:

### PR DESCRIPTION
**Pull request by brxck**
This will close #28 by migrating from the Orders API.

- Replace the usage of Skus with Prices
- Remove any functionality to do with inventory (depended on Skus)
- Add fixtures to seed Products and Prices #29 
- Fix sending requests to functions which require authentication

This depends on a pending pull request I have made to gatsby-source-stripe.

### CODE REVIEW

**Comment by AtActionPark** [comment]
Hello! I've been using your starter and I was trying to convert to prices too but I encountered an issue:
As per stripe documentation, the price api does not support deletion.
The current productDelete function will fail, and trying to delete a product without deleting the prices might fail too.

As far as I know, the recommended way is to set the product as inactive via api, or archive/delete manually on the stripe dashboard.

Maybe I'm missing something though.

Cheers

**Comment by brxck** [comment]
Hey @AtActionPark! You are right, you cannot delete prices or products related to them. I have a bunch of work to bring back over to this starter after I finish up a related project I'm working on. There is definitely a bunch here in this PR that isn't quite right yet!

**Comment by michalien** [comment]
Hi Brock, I downloaded this starter a few days ago and manually applied some of your migration commits. Builds still error out with no display in the browser. Just wondering if you have any roadmap for the changes needed to complete the migration from Skus to Prices API so the starter completes a successful development build?
Many thanks, Mike

**Comment by michalien** [comment]
@brxck after appying all your migration commits, netlify dev still failed with error: nickname and localFiles not found in graphQL. Providing a type definition for nickname (per Gatsby docs /schema-customization) the starter runs and completes payments in dev, but fails a netlify deploy build with localFiles not found in graphQL. Assuming the lack of a type def is the cause but no success on the correct syntax. Can you please help with a type definition for localFiles? Many thanks, Mike

**Comment by michalien** [comment]
@brxck is there any eta on merging your changes to the @njosefbeck source plugin... The source/starter combo works nicely in dev but otherwise I’m stuck with failing Netlify builds. Do we go on waiting, or manually patch in the changes in our own installation?

**Comment by brxck** [comment]
Sorry for the delay, but as things currently stand I'll be unable to make any changes for some time. 

Please feel free to make any changes required to get this merged.

**Pull request merged**
